#!/usr/bin/env python3
"""Generate the samples for the sample explorer, and the manifest that lists them. Standard library only.

Each sample is four bars (16 beats) at 112 BPM, mono 16-bit, in A minor (Am, F, C, G). Reverb tails
wrap around, so every sample loops seamlessly. The builders live in sample_drums, sample_tones and
sample_textures; the group order below is the order of the explorer list.

    python3 scripts/generate_samples.py            # everything
    python3 scripts/generate_samples.py kick-four  # only the named samples (the manifest is always rewritten)
"""
import math, os, sys
from multiprocessing import Pool
from synth import reverb, write_wav
from sample_core import seed
import sample_drums, sample_tones, sample_textures

DIST = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'dist')
OUT = os.path.join(DIST, 'audio', 'samples')

BUILDERS = {id: (name, build) for module in (sample_drums, sample_tones, sample_textures) for id, name, build in module.SAMPLES}
GROUPS = [
    ('Drums', ['kick-four', 'kick-broken', 'snare-backbeat', 'snare-roll', 'clap', 'rim-clave', 'hats-eighths', 'hats-sixteenths', 'open-hats', 'trap-hats',
               'toms', 'congas', 'tambourine', 'shaker', 'cowbell', 'break', 'kit-straight', 'kit-halftime', 'crash']),
    ('Bass', ['sub-bass', 'saw-bass', 'pluck-bass', '808-bass', 'acid', 'square-bass', 'wobble']),
    ('Keys & Pads', ['piano', 'piano-arp', 'electric-piano', 'organ', 'vibraphone', 'pizzicato', 'synth-stabs', 'strings', 'pad-warm', 'pad-glass', 'pad-dark']),
    ('Melody', ['arp-pluck', 'arp-bell', 'lead-saw', 'lead-chip', 'marimba', 'kalimba', 'music-box', 'bells', 'guitar', 'harp', 'flute']),
    ('Voices', ['choir-ah', 'choir-oo', 'choir-low']),
    ('Textures & FX', ['vinyl', 'rain', 'wind', 'waves', 'riser', 'downlifter', 'impact', 'drone', 'pulse-gate', 'cymbal-swell']),
]
assert sorted(id for _, ids in GROUPS for id in ids) == sorted(BUILDERS), 'every sample belongs to exactly one group'

# Samples are matched in loudness, as far as their peaks allow, so a pad and a hi-hat sit together.
TARGET_RMS, CEILING = .14, .85


def render(id):
    seed(id)
    samples, room = BUILDERS[id][1]()
    samples = reverb(samples, room)
    mean = sum(samples) / len(samples)
    samples = [v - mean for v in samples]
    peak = max(abs(v) for v in samples) or 1
    rms = math.sqrt(sum(v * v for v in samples) / len(samples)) or 1
    gain = min(CEILING / peak, TARGET_RMS / rms)
    write_wav(os.path.join(OUT, id + '.wav'), [v * gain for v in samples])
    return id


def write_manifest():
    rows = ',\n'.join(f"['{id}','{BUILDERS[id][0]}','{group}']" for group, ids in GROUPS for id in ids)
    with open(os.path.join(DIST, 'samples.js'), 'w') as f:
        f.write("'use strict';\n// Samples for the explorer; generated by scripts/generate_samples.py.\n"
                f"window.MUSIC_SAMPLES=[\n{rows}\n].map(([id,name,group])=>({{id,name,group,beats:16,file:`audio/samples/${{id}}.wav`}}));\n")


if __name__ == '__main__':
    wanted = sys.argv[1:] or list(BUILDERS)
    unknown = [id for id in wanted if id not in BUILDERS]
    if unknown:
        sys.exit('Unknown sample: ' + ', '.join(unknown))
    os.makedirs(OUT, exist_ok=True)
    with Pool() as pool:
        for id in pool.imap_unordered(render, wanted):
            print(id, flush=True)
    write_manifest()
